### PR TITLE
Fix duplicate symbols error in xcode

### PR DESCRIPTION
**Pull request by gitim**
Hi. After upgrading to 1.1 our build is broken, Xcode build command fails with `duplicate symbols` errors.

 I searched in stackOverflow for such issues and seems, that it happens because of importing `.m` file from BlurView.m, there are [recommendations](http://stackoverflow.com/a/22877819) to import `.h` files instead. So, in this pr I splitted interface and implementation of BlurAmount and replace `"BlurAmount.m"` with `"BlurAmount.h"`
 in import. These changes won't anyhow affect users.

### CODE REVIEW

**Comment by f-roland** [comment]
@gitim do you know when will this PR be merged ?

**Comment by gitim** [comment]
No, I am still waiting a review from @Kureev

**Comment by Kureev** [comment]
Hi @gitim! Thanks for your contribution and sorry for the late review. 

It will be great if somebody can update examples as well.

**Comment by Kureev** [comment]
btw, 1.2.1 has been released
